---
swagger: "2.0"
info:
  description: Swagger File
  version: 1.0.0
  title: Network-Project
host: virtserver.swaggerhub.com
basePath: /Ssathwik-Reddy/Network-project/1.0.0
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /people:
    get:
      tags:
      - People
      summary: Read the entire list of people
      description: Read the list of people
      operationId: people.read_all
      parameters:
      - name: length
        in: query
        description: Number of people to get from people
        required: false
        type: integer
      - name: offset
        in: query
        description: Offset from beginning of list where to start gathering people
        required: false
        type: integer
      responses:
        200:
          description: Successfully read people list operation
          schema:
            type: array
            items:
              type: object
              properties:
                fname:
                  type: string
                lname:
                  type: string
                timestamp:
                  type: string
    post:
      tags:
      - People
      summary: Create a person and add it to the people list
      description: Create a new person in the people list
      operationId: people.create
      parameters:
      - in: body
        name: person
        description: Person to create
        required: true
        schema:
          $ref: '#/definitions/person'
      responses:
        201:
          description: Successfully created person in list
  /people/{lname}:
    get:
      tags:
      - People
      summary: Read one person from the people list
      description: Read one person from the people list
      operationId: people.read_one
      parameters:
      - name: lname
        in: path
        description: Last name of the person to get from the list
        required: true
        type: string
      responses:
        200:
          description: Successfully read person from people list operation
          schema:
            properties:
              fname:
                type: string
              lname:
                type: string
              timestamp:
                type: string
    put:
      tags:
      - People
      summary: Update a person in the people list
      description: Update a person in the people list
      operationId: people.update
      parameters:
      - name: lname
        in: path
        description: Last name of the person to update in the list
        required: true
        type: string
      - in: body
        name: person
        required: false
        schema:
          $ref: '#/definitions/person_1'
      responses:
        200:
          description: Successfully updated person in people list
    delete:
      tags:
      - People
      summary: Delete a person from the people list
      description: Delete a person
      operationId: people.delete
      parameters:
      - name: lname
        in: path
        required: true
        type: string
      responses:
        200:
          description: Successfully deleted a person from people list
definitions:
  person:
    type: object
    properties:
      fname:
        type: string
        description: First name of person to create
      lname:
        type: string
        description: Last name of person to create
  inline_response_200:
    properties:
      fname:
        type: string
      lname:
        type: string
      timestamp:
        type: string
  person_1:
    type: object
    properties:
      fname:
        type: string
      lname:
        type: string
